### ISSUE TITLE
How to configure for https?

### ISSUE THREAD

**Issue by BrianGilbert** [organizrTools/docker-organizr-v2#2]
Want to run over https so I can have tabs that load external https sites..

**Comment by BrianGilbert** [comment]
looks like it may be as simple as exposing the port https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/Dockerfile

**Comment by BrianGilbert** [comment]
https://github.com/organizrTools/docker-organizr-v2/compare/master...BrianGilbert:patch-1

**Comment by Roxedus** [comment]
We are probably never gonna support this, You are meant to reverse proxy this docker.

**Comment by causefx** [comment]
I think we should do this for ppl that only run it locally and dont proxy it.
