### ISSUE TITLE
arm64 option

### ISSUE THREAD

**Issue by XtracT** [organizrTools/docker-organizr-v2#4]
Hi!

I am currently running organizr-v2 in an arm64 environment, just by using lsiobase/alpine.nginx.arm64:3.8 as a base. Do you thing it would be possible to add it as a tag?

Thanks for the awesome work!

/Xtract

**Comment by Thijzer** [comment]
If you need a tester I'm up for it.

**Comment by tronyx** [comment]
Working on it tonight. Thanks for the input and base image reference.

**Comment by tronyx** [comment]
Alright, have an image for you to test: organizrtools/organizr-v2:dev-arm64

**Comment by Thijzer** [comment]
pm @christronyxyocum 
Looks like 
- the build is working
- the setup worked and made a database
- my nginx reverse proxy is working as well

so many kudos to you, you have a working arm64 version.

**Comment by tronyx** [comment]
Awesome! Thanks for testing. There is now `:arm64` for the v2-master branch and `dev-arm64` for the v2-develop branch. Once @XtracT confirms as well I will close this out.

**Comment by XtracT** [comment]
Yes, started it before on :dev-arm64, worked nicely and now just switched to the master branch. Thank you for your work! Any tests you think we should do please let me know, otherwise just close this.

/Xtract

**Comment by tronyx** [comment]
No problem! Thank you for opening the issue and for providing a base image for us to use. Will close this now, but feel free to reach out on Discord if you encounter any issues.
