### ISSUE TITLE
Docker container wont stop - process s6-sync stuck

### ISSUE THREAD

**Issue by yesluv** [organizrTools/docker-organizr-v2#5]
Cannot stop, restart or kill docker container. All other containers respond fine so dont think this is an issue with docker itself. When trying to stop organizr container, it just hangs indefinatly, trying stop and kill from cmd doesnt help. Looking at container, it appears to be stuck with only process left running s6-sync

only option is to restart docker, but this is far from ideal since all other containers will restart

Any help would be greatly appreciated

Synology DSM 6.2 (Docker Version: 17.05.0-0400)

crond[352]: USER root pid 613 cmd run-parts /etc/periodic/15min
[26-Mar-2019 16:45:25] NOTICE: Terminating ...
[26-Mar-2019 16:45:25] NOTICE: exiting, bye-bye!
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.

no

**Comment by tronyx** [comment]
What is in the container logs in their entirety? Have not had any other complaints of this. It could be something with an older version of Docker too. Please try pulling the image to make sure you're running the latest as well.

**Comment by causefx** [comment]
```
5b48a9586c56        organizrtools/organizr-v2:dev-php-fpm       "/init"                  2 minutes ago       Exited (0) 3 seconds ago                                                                                                                                         organizrV2
```

I just tested after pulling a new image and stopping the container was fine.

**Comment by tronyx** [comment]
Also, make sure that you're not specifying the root user for the UID and GID when you created the container. PHP does not like running as root.

**Comment by yesluv** [comment]
Sorry, all. I may have been a bit hasty reporting this as an issue. I noticed a backup running in the background via Synology HyperBackup, once i stopped the backup, docker behaved itself. If anyone else has this issue then its most likely due something else like that

thanks again all for quick responses
