### ISSUE TITLE
Support multi-arch deploys with Manifests

### ISSUE THREAD

**Issue by NickBusey** [organizrTools/docker-organizr-v2#9]
Currently Organizr tags it's separate architecture images differently.

The `latest` tag is only `amd64`, to use this image on ARM, you have to point it to an architecture specific tag like `arm64` or `armhf`.

This complicates deployment and causes unnecessary user friction.

Nextcloud for example, does this correctly. Their `latest` tag supports a whole slew of architectures.

Take a look at https://hub.docker.com/_/nextcloud/?tab=tags vs https://hub.docker.com/r/organizrtools/organizr-v2/tags to see what I mean.

If Organizr could use docker manifests the way Nextcloud does, I wouldn't have to do things like this in my ansible code:

```
    image: organizrtools/organizr-v2:{{ 'armhf' if arm else 'latest' }}
```

**Comment by tronyx** [comment]
Yeah, we're aware, and have been for some time, but it requires time which, I specifically, do not have. It's definitely something we want to do, but we have no ETA at this time.

**Comment by NickBusey** [comment]
Ok, I would be willing to help on this if it's desired.

**Comment by tronyx** [comment]
Thanks, we appreciate it. One of the other members, I believe, has experience with the manifests so I've started a conversation with him and CauseFX about this.

Chris
 

    On Tuesday, April 7, 2020, 11:17:25 AM EDT, Nick Busey <notifications@github.com> wrote:  
 
 


Ok, I would be willing to help on this if it's desired.

**Comment by Roxedus** [comment]
This has been on the timeline for a while, and two of the three criterias has been filled for a few months, the last piece of the puzzle is php7.4 hitting the alpine package repo.
